### PR TITLE
Add ability for iconsPath option to be a callback

### LINKED ISSUE #15: Path Prefix
Nice Plugin! Thx!
It would be nice if there was an option to prefix the "icons_path" variable. Maybe there is another way to insert something like "<?php print $somepath; ?>" in front of the "icons_path"?

### PR DESCRIPTION
**Pull request by markcarver**
Fixes #15 

Note: if you're in dire need to use this (until an official release can be made), you can simply require the following:

```bash
npm install grunt-real-favicon@https://github.com/markcarver/grunt-real-favicon/archive/callback.tar.gz --save-dev
```

A complete example using a callback to generate dynamic paths for use in a [Drupal Bootstrap](https://www.drupal.org/project/bootstrap) (twig based) theme:
```js
var fs = require('fs');
var path = require('path');

module.exports = function (grunt) {
  'use strict';

  // Find the absolute local path of the [Drupal] docroot.
  var docroot;
  var directories = __dirname.split(path.sep);
  while (directories.length) {
    docroot = directories.join(path.sep);
    if (fs.existsSync(docroot + path.sep + '/index.php')) {
      break;
    }
    directories.pop();
  }

  // Normalizes a local file system path to be used as URL.
  var pathToUrl = function () {
    return Array.prototype.slice.call(arguments).join('/').replace(/\\+|\/+/g, '/').replace(/\/+/g, '/');
  };

  // Remove the docroot prefix from current directory to determine themeRoot
  // and normalize its local path to be a relative URL.
  var themeRoot = pathToUrl(__dirname.replace(new RegExp('^' + docroot), '')));

  // Create a random string to use as a cache buster in query strings.
  var cacheBuster = Math.random().toString(36).substr(2, 7).toUpperCase();

  var faviconDir = 'img/favicons';

  // Load grunt task(s).
  grunt.loadNpmTasks('grunt-real-favicon');

  // Initialize config for grunt task(s).
  grunt.initConfig({
    realFavicon: {
      favicons: {
        src: 'src/img/favicon.png',
        dest: faviconDir,
        options: {
          /**
           * Returns the path prefix that should be used to generate favicons.
           *
           * @param {String} href
           *   The matched favicon file name.
           * @param {String} file
           *   The source file from which the href came from.
           *
           * @return {String}
           *   A path prefix.
           */
          iconsPath: function (href, file) {
            var json = /\.json$/.test(file);
            var xml = /\.xml$/.test(file);
            // Handle meta files differently since they're static, not processed
            // by the server and require absolute/relative URL paths.
            if (json || xml) {
              href = pathToUrl(themeRoot, faviconDir, href + '?' + cacheBuster);
              // Ensure path separators in manifest.json are properly escaped.
              return json ? href.replace(/\/+/g, '\\/') : href;
            }

            // Otherwise, return Twig output to dynamically generate the path.
            return '{{ file_url(theme.path ~ "/' + grunt.pathToUrl(faviconDir, href) + '?" ~ theme.query_string) }}';
          }
          html: ['templates/system/favicons.html.twig'],
          // Other options.
        }
        // Rest of config.
      }
    }
  });

};
```

Then, in `templates/system/page.html.twig`, include the generated output:
```twig
{% include 'favicons.html.twig' %}
```

### CODE REVIEW

**Comment by phbernard** [comment]
Thank you @markcarver for the PR! This change definitely makes sense.

I reviewed your code. I didn't test it yet but it looks fine to me, except for one point: it hardcodes the file names `browserconfig.xml` and `manifest.json`. The design of RFG API and its clients it to put as many "favicon knowledge" as possible in the API, and as few as possible in the clients. For example, the search-and-replace procedure won't work if the icon for Yandex browser is generated (it relies on a file named `yandex-browser-manifest.json`; this platform is only accessible through the API).

I see two ways to handle this:

- As this pattern is common (the Rails plugin does something similar), the API could return the list of files where the path (might) appear. So a client could blindly iterate over these files to do a search-and-replace or whatever. I think this is the best solution, but this is not something I plan to work on right now.
- Simply replace the hardcoded files by two `.xml` and `.json` extension check. This is what the Rails plugin does as of today.

You or I can do this (I certainly not ask you to do this!), just let me know.

**Comment by markcarver** [comment]
Yeah, I wasn't sure about that bit honestly. It does make sense to just do this by extension (for now). Perhaps in the future it can be refactored to take advantage of whatever "meta" files are provided by the API.

I can change this, it's relatively easy enough.

**Comment by markcarver** [comment]
PR updated to take into account any `json` or `xml` generated file.

**Comment by phbernard** [comment]
Great! Thank you!

I updated the unit tests so that `iconsPathCallback` is tested, too.

**Pull request merged**
